name="Konos"
version="1.0.0"
changeNotes=""
gulpFileTemplate="io.intino.konos.builder.codegeneration.accessor.ui.gulp.Gulpfile_jsTemplate.class"
packageJsonTemplate="io.intino.konos.builder.codegeneration.accessor.ui.gulp.Package_jsonTemplate.class"

[[groups]]
id="KonosToolsGroup"
popup="true"
text="Konos"
aClass="io.intino.konos.builder.actions.KonosActionGroup"
groupId="ToolsMenu"
anchor="last"

[[actions]]
id="NewKonosFile"
aClass="io.intino.konos.builder.actions.CreateKonosFileAction"
groupId="NewGroup"
relativeToAction="NewTaraFile"
anchor="first"

[[actions]]
id="CreateKonosAPI"
aClass="io.intino.konos.builder.actions.CreateKonosBoxAction"
text="Create Konos Shell"
description="Create Konos Shell"
shortcut="control alt S"
groupId="KonosToolsGroup"

[[actions]]
id="PublishAccesors"
aClass="io.intino.konos.builder.actions.PublishAccessorAction"
text="Distribute Konos Accessor"
description="Distribute Konos Accessor in Artifactory"
shortcut="control alt A"
groupId="KonosToolsGroup"