name="Konos"
version="1.0.0"
changeNotes=""
gulpFileTemplate="io.intino.konos.builder.codegeneration.accessor.ui.gulp.Gulpfile_jsTemplate.class"
packageJsonTemplate="io.intino.konos.builder.codegeneration.accessor.ui.gulp.Package_jsonTemplate.class"

[[actions]]
id="NewKonosFile"
aClass="io.intino.konos.builder.actions.CreateKonosFileAction"
groupId="NewGroup"
relativeToAction="NewTaraFile"
anchor="first"

[[actions]]
id="CreateKonosBox"
aClass="io.intino.konos.builder.actions.CreateKonosBoxAction"
text="Create Konos Box"
description="Create Konos Box"
shortcut="control alt S"
groupId="intino"
anchor="first"

[[actions]]
id="PublishAccessors"
aClass="io.intino.konos.builder.actions.PublishAccessorAction"
text="Distribute Konos Accessors"
description="Distribute Konos Accessors in Artifactory"
shortcut="control alt A"
groupId="intino"
anchor="first"
