package io.intino.konos.builder.codegeneration.services.activity.display.prototypes;

import org.siani.itrules.*;

import java.util.Locale;

import static org.siani.itrules.LineSeparator.*;

public class AbstractMoldTemplate extends Template {

	protected AbstractMoldTemplate(Locale locale, LineSeparator separator) {
		super(locale, separator);
	}

	public static Template create() {
		return new AbstractMoldTemplate(Locale.ENGLISH, LF).define();
	}

	public Template define() {
		add(
			rule().add((condition("type", "mold"))).add(literal("package ")).add(mark("package")).add(literal(".displays;\n\nimport io.intino.konos.alexandria.activity.displays.AlexandriaMold;\nimport io.intino.konos.alexandria.activity.model.Mold;\nimport io.intino.konos.alexandria.activity.model.mold.Block;\nimport io.intino.konos.alexandria.activity.model.mold.Stamp;\nimport io.intino.konos.alexandria.activity.model.mold.stamps.*;\nimport ")).add(mark("package", "validPackage")).add(literal(".")).add(mark("box", "firstUpperCase")).add(literal("Box;\nimport ")).add(mark("package", "validPackage")).add(literal(".displays.notifiers.")).add(mark("name", "firstUpperCase")).add(literal("Notifier;\n\npublic abstract class Abstract")).add(mark("name", "FirstUpperCase")).add(literal(" extends AlexandriaMold<")).add(mark("name", "FirstUpperCase")).add(literal("Notifier> {\n\n\tpublic Abstract")).add(mark("name", "FirstUpperCase")).add(literal("(")).add(mark("box", "FirstUpperCase")).add(literal("Box box) {\n\t\tsuper(box);\n\t\telement(buildMold(box));\n\t}\n\n\tpublic Mold buildMold(")).add(mark("box", "FirstUpperCase")).add(literal("Box box) {\n\t\tMold mold = new Mold()")).add(mark("block", "definition").multiple("\n")).add(literal(";\n\t\treturn mold;\n\t}\n\n\tprivate java.net.URL urlOf(String url)  {\n\t\ttry {\n\t\t\treturn new java.net.URL(url);\n\t\t} catch (java.net.MalformedURLException e) {\n\t\t\treturn null;\n\t\t}\n\t}\n}")),
			rule().add((condition("type", "block")), (condition("trigger", "definition"))).add(literal(".add(new Block()")).add(expression().add(literal(".name(\"")).add(mark("name")).add(literal("\")"))).add(expression().add(mark("expanded"))).add(expression().add(mark("layout").multiple(""))).add(expression().add(mark("height"))).add(expression().add(mark("width"))).add(expression().add(mark("hidden"))).add(expression().add(mark("hiddenIfMobile"))).add(expression().add(mark("style"))).add(expression().add(literal("\n")).add(literal("\t")).add(mark("stamp").multiple("\n\t\t"))).add(expression().add(literal("\n")).add(literal("\t")).add(mark("block", "definition").multiple("\n"))).add(literal(")\n")),
			rule().add((condition("trigger", "height"))).add(literal(".height(")).add(mark("value")).add(literal(")")),
			rule().add((condition("trigger", "width"))).add(literal(".width(")).add(mark("value")).add(literal(")")),
			rule().add((condition("attribute", "hiddenEnabled")), (condition("trigger", "hidden"))).add(literal(".hidden((object) -> ")).add(mark("mold", "FirstUpperCase")).add(literal(".Stamps.")).add(mark("name", "FirstUpperCase")).add(literal(".hidden((")).add(mark("moldClass")).add(literal(") object))")),
			rule().add((condition("trigger", "hidden"))),
			rule().add((condition("trigger", "hiddenIfMobile"))).add(literal(".hiddenIfMobile(")).add(mark("value")).add(literal(")")),
			rule().add((condition("trigger", "layout"))).add(literal(".add(Block.Layout.")).add(mark("value", "FirstUpperCase")).add(literal(")")),
			rule().add((condition("type", "stamp & location"))).add(literal(".add(new io.intino.konos.alexandria.activity.model.mold.stamps.Location()")).add(expression().add(mark("icon"))).add(mark("common")).add(literal(")")),
			rule().add((condition("type", "stamp & breadcrumbs"))).add(literal(".add(new io.intino.konos.alexandria.activity.model.mold.stamps.Breadcrumbs()")).add(mark("common")).add(literal(")")),
			rule().add((condition("type", "stamp & cataloglink"))).add(literal(".add(new io.intino.konos.alexandria.activity.model.mold.stamps.CatalogLink()")).add(expression().add(literal(".filter(")).add(mark("filter")).add(literal(")"))).add(mark("common")).add(literal(")")),
			rule().add((condition("type", "stamp & embeddedCatalog"))).add(literal(".add(new io.intino.konos.alexandria.activity.model.mold.stamps.EmbeddedCatalog().display((io.intino.konos.alexandria.activity.displays.AlexandriaCatalog) ElementDisplays.displayFor(box, \"")).add(mark("catalog")).add(literal("\")).catalog((io.intino.konos.alexandria.activity.model.Catalog) ElementDisplays.displayFor(box, \"")).add(mark("catalog")).add(literal("\").element())")).add(expression().add(literal(".filter(")).add(mark("embeddedCatalogFilter")).add(literal(")"))).add(mark("common")).add(literal(")")),
			rule().add((condition("type", "stamp & embeddedDisplay"))).add(literal(".add(new io.intino.konos.alexandria.activity.model.mold.stamps.EmbeddedDisplay().displayType(\"")).add(mark("displayType")).add(literal("\").displayBuilder(")).add(mark("displayBuilder")).add(literal(")")).add(mark("common")).add(literal(")")),
			rule().add((condition("type", "stamp & highlight"))).add(literal(".add(new io.intino.konos.alexandria.activity.model.mold.stamps.Highlight().color((object, username) -> ")).add(mark("mold", "FirstUpperCase")).add(literal(".Stamps.")).add(mark("name", "FirstUpperCase")).add(literal(".color(box, (")).add(mark("moldClass")).add(literal(") object, username))")).add(mark("common")).add(literal(")")),
			rule().add((condition("type", "stamp & itemLinks"))).add(literal(".add(new io.intino.konos.alexandria.activity.model.mold.stamps.ItemLinks().title(")).add(mark("title")).add(literal(")")).add(mark("common")).add(literal(")")),
			rule().add((condition("type", "stamp & polymerIcon"))).add(literal(".add(new io.intino.konos.alexandria.activity.model.mold.stamps.icons.AlexandriaIcon().title(")).add(mark("title")).add(literal(")")).add(mark("common")).add(literal(")")),
			rule().add((condition("type", "stamp & resourceIcon"))).add(literal(".add(new io.intino.konos.alexandria.activity.model.mold.stamps.icons.ResourceIcon().title(")).add(mark("title")).add(literal(")")).add(mark("common")).add(literal(")")),
			rule().add((condition("type", "stamp & base64Icon"))).add(literal(".add(new io.intino.konos.alexandria.activity.model.mold.stamps.icons.Base64Icon().title(")).add(mark("title")).add(literal(")")).add(mark("common")).add(literal(")")),
			rule().add((condition("type", "stamp & rating"))).add(literal(".add(new io.intino.konos.alexandria.activity.model.mold.stamps.Rating()")).add(expression().add(literal(".ratingIcon(")).add(mark("ratingIcon", "quoted")).add(literal(")"))).add(mark("common")).add(literal(")")),
			rule().add((condition("type", "stamp & picture"))).add(literal(".add(new io.intino.konos.alexandria.activity.model.mold.stamps.Picture()")).add(expression().add(literal(".defaultPicture(urlOf(\"")).add(mark("defaultPicture")).add(literal("\"))"))).add(mark("common")).add(literal(")")),
			rule().add((condition("type", "stamp & openDialogOperation"))).add(literal(".add(new io.intino.konos.alexandria.activity.model.mold.stamps.operations.OpenDialogOperation()")).add(expression().add(mark("width"))).add(expression().add(literal(".path(")).add(mark("dialogPath")).add(literal(")"))).add(mark("common")).add(literal(")")),
			rule().add((condition("type", "stamp & downloadOperation"))).add(literal(".add(new io.intino.konos.alexandria.activity.model.mold.stamps.operations.DownloadOperation()")).add(expression().add(literal(".options(java.util.Arrays.asList(")).add(mark("options", "quoted").multiple(", ")).add(literal("))"))).add(literal(".execution(")).add(mark("downloadexecution")).add(literal(")")).add(mark("common")).add(literal(")")),
			rule().add((condition("type", "stamp & taskOperation"))).add(literal(".add(new io.intino.konos.alexandria.activity.model.mold.stamps.operations.TaskOperation().execution(")).add(mark("taskexecution")).add(literal(")")).add(mark("common")).add(literal(")")),
			rule().add((condition("type", "stamp & exportOperation"))).add(literal(".add(new io.intino.konos.alexandria.activity.model.mold.stamps.operations.ExportOperation()\n\t")).add(expression().add(literal(".from(java.time.Instant.ofEpochMilli(")).add(mark("from")).add(literal("L))"))).add(literal("\n\t")).add(expression().add(literal(".to(java.time.Instant.ofEpochMilli(")).add(mark("to")).add(literal("L))"))).add(literal("\n\t")).add(expression().add(literal(".options(java.util.Arrays.asList(")).add(mark("options", "quoted").multiple(", ")).add(literal("))"))).add(literal("\n\t.execution(")).add(mark("exportexecution")).add(literal(")")).add(mark("common")).add(literal(")")),
			rule().add((condition("type", "stamp"))).add(literal(".add(new ")).add(mark("type", "FirstUpperCase")).add(literal("()")).add(mark("common")).add(literal(")")),
			rule().add((condition("trigger", "common"))).add(expression().add(literal(".name(\"")).add(mark("name")).add(literal("\")"))).add(expression().add(literal(".label(\"")).add(mark("label")).add(literal("\")"))).add(expression().add(mark("height"))).add(expression().add(literal("\n")).add(literal(".defaultStyle(\"")).add(mark("defaultStyle")).add(literal("\")"))).add(expression().add(literal(".suffix(\"")).add(mark("suffix")).add(literal("\")"))).add(expression().add(literal("\n")).add(literal(".layout(Stamp.Layout.")).add(mark("layout")).add(literal(")"))).add(expression().add(literal(".editable(")).add(mark("editable")).add(literal(")"))).add(expression().add(literal("\n")).add(mark("style"))).add(literal("\n")).add(mark("valueMethod")),
			rule().add((condition("trigger", "style"))).add(literal(".style((object, username) -> ")).add(mark("mold", "FirstUpperCase")).add(literal(".Stamps.")).add(mark("name", "firstUpperCase")).add(literal(".style(box, (")).add(mark("moldClass")).add(literal(") object, username))")),
			rule().add((condition("trigger", "embeddedCatalogFilter"))).add(literal("(element, source, target, username) -> ")).add(mark("mold", "FirstUpperCase")).add(literal(".Stamps.")).add(mark("name", "FirstUpperCase")).add(literal(".filter(box, element, source, target, username)")),
			rule().add((condition("trigger", "displayBuilder"))).add(literal("(name, username) -> ")).add(mark("mold", "FirstUpperCase")).add(literal(".Stamps.")).add(mark("name", "FirstUpperCase")).add(literal(".buildDisplay(box, name, username)")),
			rule().add((condition("trigger", "title"))).add(literal("(object, username) -> ")).add(mark("mold", "FirstUpperCase")).add(literal(".Stamps.")).add(mark("name", "FirstUpperCase")).add(literal(".title(box, (")).add(mark("moldClass")).add(literal(") object, username)")),
			rule().add((condition("trigger", "dialogPath"))).add(literal("(object, username) -> ")).add(mark("mold", "FirstUpperCase")).add(literal(".Stamps.")).add(mark("name", "FirstUpperCase")).add(literal(".path(box, (String) object, username)")),
			rule().add((condition("trigger", "exportExecution"))).add(literal("(object, from, to, option, username) -> ")).add(mark("mold", "FirstUpperCase")).add(literal(".Stamps.")).add(mark("name", "FirstUpperCase")).add(literal(".execute(box, (")).add(mark("moldClass")).add(literal(") object, from, to, option, username)")),
			rule().add((condition("trigger", "downloadExecution"))).add(literal("(object, option, username) -> ")).add(mark("mold", "FirstUpperCase")).add(literal(".Stamps.")).add(mark("name", "FirstUpperCase")).add(literal(".execute(box, (")).add(mark("moldClass")).add(literal(") object, option, username)")),
			rule().add((condition("trigger", "taskExecution"))).add(literal("(object, username) -> ")).add(mark("mold", "FirstUpperCase")).add(literal(".Stamps.")).add(mark("name", "FirstUpperCase")).add(literal(".execute(box, (")).add(mark("moldClass")).add(literal(") object, username)")),
			rule().add((condition("trigger", "filter"))).add(literal("(source, target, username) -> ")).add(mark("mold", "FirstUpperCase")).add(literal(".Stamps.")).add(mark("name", "FirstUpperCase")).add(literal(".filter(box, source, target, username)")),
			rule().add((condition("trigger", "editable"))).add(literal("(object, value, username) -> ")).add(mark("mold", "FirstUpperCase")).add(literal(".Stamps.")).add(mark("name", "FirstUpperCase")).add(literal(".onChange(box, (")).add(mark("moldClass")).add(literal(") object, value, username)")),
			rule().add((condition("trigger", "valueMethod"))).add(literal(".value((object, username) -> ")).add(mark("mold", "FirstUpperCase")).add(literal(".Stamps.")).add(mark("name", "FirstUpperCase")).add(literal(".value(box, (")).add(mark("moldClass")).add(literal(") object, username))")),
			rule().add((condition("trigger", "icon"))).add(literal(".icon((object, username) -> ")).add(mark("mold", "FirstUpperCase")).add(literal(".Stamps.")).add(mark("name", "FirstUpperCase")).add(literal(".icon(box, (")).add(mark("moldClass")).add(literal(") object, username))")),
			rule().add((condition("trigger", "expanded"))).add(literal(".expanded(")).add(mark("value")).add(literal(")")),
			rule().add((condition("trigger", "quoted"))).add(literal("\"")).add(mark("value")).add(literal("\""))
		);
		return this;
	}
}