package io.intino.konos.builder.codegeneration.accessor.ui.widget;

import org.siani.itrules.*;

import java.util.Locale;

import static org.siani.itrules.LineSeparator.*;

public class WidgetTemplate extends Template {

	protected WidgetTemplate(Locale locale, LineSeparator separator) {
		super(locale, separator);
	}

	public static Template create() {
		return new WidgetTemplate(Locale.ENGLISH, LF).define();
	}

	public Template define() {
		add(
			rule().add((condition("type", "widget & accessible"))).add(literal("<link rel=\"import\" href=\"../../lib/polymer/polymer.html\">\n<link rel=\"import\" href=\"../../lib/cotton-push/cotton-push-behavior.html\">\n<link rel=\"import\" href=\"../../lib/cotton-carrier/cotton-carrier-behavior.html\">\n<link rel=\"import\" href=\"../../lib/cotton-zombie/cotton-zombie.html\">\n<link rel=\"import\" href=\"")).add(mark("name", "camelCaseToSnakeCase")).add(literal(".html\">\n\n<script src=\"")).add(mark("name", "lowerCase")).add(literal("/requester.js\"></script>\n<script src=\"")).add(mark("name", "lowerCase")).add(literal("/notifier-listener.js\"></script>\n\n<dom-module id=\"")).add(mark("name", "camelCaseToSnakeCase")).add(literal("-proxy\">\n\n    <template>\n        <div id=\"component\"><cotton-zombie id=\"zombie\" display=\"")).add(mark("name")).add(literal("\" widget=\"")).add(mark("name")).add(literal("\"></cotton-zombie></div>\n        <div class=\"layout horizontal center center-justified\" style=\"height:100%;\" hidden><div id=\"error\" class=\"error\">[[_error]]</div></div>\n    </template>\n\n    <style>\n        :host #component {\n            height: 100%;\n        }\n        :host .error {\n            display: none;\n            color: var(--accent-color);\n            font-size: 12pt;\n        }\n    </style>\n\n    <script>\n\n        Polymer({\n            is: '")).add(mark("name", "camelCaseToSnakeCase")).add(literal("-proxy',\n\n            behaviors: [ CottonBehaviors.CarrierBehavior,\n                CottonBehaviors.PushBehavior,\n                ")).add(mark("name", "firstuppercase")).add(literal("ProxyBehaviors.Requester,\n                ")).add(mark("name", "firstuppercase")).add(literal("ProxyBehaviors.NotifierListener\n            ],\n\n            attached : function() {\n                this.listenToDisplay();\n                this.$.zombie.whenPersonified().execute((widget) => this.registerPersonifiedDisplay(widget.display.id));\n            },\n\n            _refreshError : function(msg) {\n                this.$.component.style.display = \"none\";\n                this.$.error.style.display = \"block\";\n                this.$.error.innerHTML = msg;\n            }\n\n        });\n    </script>\n</dom-module>")),
			rule().add((condition("type", "widget"))).add(literal("<link rel=\"import\" href=\"../../lib/polymer/polymer.html\">\n<link rel=\"import\" href=\"../../lib/cotton-push/cotton-push-behavior.html\">\n<link rel=\"import\" href=\"../../lib/cotton-carrier/cotton-carrier-behavior.html\">\n<link rel=\"import\" href=\"../../lib/cotton-zombie/cotton-zombie.html\">\n<link rel=\"import\" href=\"../../lib/cotton-translator/cotton-translator-behavior.html\">\n")).add(expression().add(literal("<link rel=\"import\" href=\"../../lib/alexandria-ui-elements/alexandria-")).add(mark("type", "camelCaseToSnakeCase")).add(literal(".html\">"))).add(literal("\n\n")).add(expression().add(mark("parent", "import")).add(literal("\n"))).add(literal("\n")).add(expression().add(mark("imports")).add(literal("\n"))).add(expression().add(literal("\n")).add(mark("routes", "routesImport")).add(literal("\n"))).add(literal("\n<script src=\"")).add(mark("name", "lowercase")).add(literal("/requester.js\"></script>\n<script src=\"")).add(mark("name", "lowercase")).add(literal("/notifier-listener.js\"></script>\n\n<dom-module id=\"")).add(mark("name", "camelCaseToSnakeCase")).add(literal("\">\n\n    <template>\n    \t")).add(mark("routes")).add(literal("\n    \t")).add(mark("parent")).add(literal("\n        ")).add(mark("innerDisplay").multiple("\n")).add(literal("\n        ")).add(mark("attached")).add(literal("\n        ")).add(mark("prototype")).add(literal("\n    </template>\n\n    <style>\n    </style>\n\n    <script>\n\n        const ")).add(mark("name", "firstuppercase")).add(literal("Dictionary = {\n            es: {\n            },\n            en: {\n            }\n        };\n\n        Polymer({\n            is: '")).add(mark("name", "camelCaseToSnakeCase")).add(literal("',\n\n            behaviors: [ CottonBehaviors.CarrierBehavior,\n                         CottonBehaviors.PushBehavior,\n                         CottonBehaviors.TranslatorBehavior,\n\t\t\t\t\t\t ")).add(mark("name", "firstuppercase")).add(literal("Behaviors.Requester,\n\t\t\t\t\t\t ")).add(mark("name", "firstuppercase")).add(literal("Behaviors.NotifierListener\n                         ],\n\n            properties : {\n            },\n\t\t\t")).add(mark("attached", "js")).add(literal("\n\t\t\t")).add(mark("prototype", "js")).add(literal("\n\n        });\n    </script>\n</dom-module>")),
			rule().add((condition("trigger", "routesImport"))).add(literal("<link rel=\"import\" href=\"")).add(mark("name", "lowercase")).add(literal("/")).add(mark("name", "camelCaseToSnakeCase")).add(literal("-routes.html\">")),
			rule().add((condition("trigger", "routes"))).add(literal("<")).add(mark("name", "camelCaseToSnakeCase")).add(literal("-routes></")).add(mark("name", "camelCaseToSnakeCase")).add(literal("-routes>")),
			rule().add((condition("trigger", "imports"))).add(literal("<script src=\"../../lib/alexandria-ui-elements/alexandria")).add(mark("type", "snakecaseToCamelCase", "lowercase")).add(literal("/requester.js\"></script>\n<script src=\"../../lib/alexandria-ui-elements/alexandria")).add(mark("type", "snakecaseToCamelCase", "lowercase")).add(literal("/notifier-listener.js\"></script>")),
			rule().add((condition("trigger", "attached")), (condition("trigger", "js"))).add(literal("attached : function() {\n\tthis.translate(")).add(mark("widget", "firstuppercase")).add(literal("Dictionary);\n\tthis.listenToDisplay();\n}")),
			rule().add((condition("type", "attached"))),
			rule().add((condition("type", "prototype")), (condition("trigger", "js"))).add(literal("attached : function() {\n\tthis.translate(")).add(mark("widget", "firstuppercase")).add(literal("Dictionary);\n\tthis._linkWithAlexandriaElement();\n\tthis.listenToDisplay();\n},\n\n_linkWithAlexandriaElement : function() {\n\tvar element = this.querySelector(\"alexandria-")).add(mark("type", "camelCaseToSnakeCase")).add(literal("\");\n\telement.display = this.display;\n\telement.behaviors.push(Alexandria")).add(mark("type", "snakeCaseToCamelCase", "firstuppercase")).add(literal("Behaviors.Requester);\n\telement.behaviors.push(Alexandria")).add(mark("type", "snakeCaseToCamelCase", "firstuppercase")).add(literal("Behaviors.NotifierListener);\n\telement.behaviors.push(")).add(mark("widget", "firstuppercase")).add(literal("Behaviors.NotifierListener);\n\tfor (var i in ")).add(mark("widget", "firstuppercase")).add(literal("Behaviors.Requester) element[i] = ")).add(mark("widget", "firstuppercase")).add(literal("Behaviors.Requester[i];\n\telement.listenToDisplay();\n}")),
			rule().add((condition("type", "prototype"))).add(literal("<alexandria-")).add(mark("type", "camelCaseToSnakeCase")).add(literal("></alexandria-")).add(mark("type", "camelCaseToSnakeCase")).add(literal(">")),
			rule().add((condition("trigger", "import"))).add(literal("<link rel=\"import\" href=\"../../lib/")).add(mark("dsl", "lowercase")).add(literal("/")).add(mark("value", "lowercase")).add(literal(".html\">")),
			rule().add((condition("trigger", "innerDisplay"))).add(literal("<div><cotton-zombie display=\"")).add(mark("value")).add(literal("\" widget=\"")).add(mark("value")).add(literal("\"></cotton-zombie></div>")),
			rule().add((condition("trigger", "parent"))).add(literal("<div><cotton-zombie display=\"")).add(mark("value")).add(literal("\" widget=\"")).add(mark("value")).add(literal("\"></cotton-zombie></div>"))
		);
		return this;
	}
}