package io.intino.konos.builder.codegeneration.services.ui.display.toolbar;

import io.intino.itrules.RuleSet;
import io.intino.itrules.Template;

public class OperationTemplate extends Template {

	public RuleSet ruleSet() {
		return new RuleSet().add(
				rule().condition((allTypes("download", "operation"))).output(literal("public static io.intino.alexandria.ui.Resource download(")).output(mark("box", "firstUpperCase")).output(literal("Box box, io.intino.alexandria.ui.model.")).output(mark("ownerClass")).output(literal(" ")).output(mark("ownerClass", "firstLowerCase")).output(literal(", String option, String selfId, UISession session) {\n\treturn null;\n}")),
				rule().condition((allTypes("operation", "export"))).output(literal("public static io.intino.alexandria.ui.Resource export(")).output(mark("box", "firstUpperCase")).output(literal("Box box, io.intino.alexandria.ui.model.")).output(mark("ownerClass")).output(literal(" ")).output(mark("ownerClass", "firstLowerCase")).output(literal(", java.time.Instant from, java.time.Instant to, String selfId, UISession session) {\n\treturn null;\n}")),
				rule().condition((allTypes("task", "operation"))).output(literal("public static io.intino.alexandria.ui.model.toolbar.ToolbarResult task(")).output(mark("box", "firstUpperCase")).output(literal("Box box, io.intino.alexandria.ui.model.")).output(mark("ownerClass")).output(literal(" ")).output(mark("ownerClass", "firstLowerCase")).output(literal(", String selfId, UISession session) {\n\treturn io.intino.alexandria.ui.model.toolbar.ToolbarResult.none();\n}")),
				rule().condition((allTypes("downloadselection", "operation"))).output(literal("public static io.intino.alexandria.ui.Resource downloadSelection(")).output(mark("box", "firstUpperCase")).output(literal("Box box, io.intino.alexandria.ui.model.Catalog catalog, String option, java.util.List<")).output(mark("itemClass")).output(literal("> selection, String selfId, UISession session) {\n\treturn null;\n}")),
				rule().condition((allTypes("exportselection", "operation"))).output(literal("public static io.intino.alexandria.ui.Resource exportSelection(")).output(mark("box", "firstUpperCase")).output(literal("Box box, io.intino.alexandria.ui.model.Catalog catalog, java.time.Instant from, java.time.Instant to, java.util.List<")).output(mark("itemClass")).output(literal("> selection, String selfId, UISession session) {\n\treturn null;\n}")),
				rule().condition((allTypes("taskselection", "operation"))).output(literal("public io.intino.alexandria.ui.model.toolbar.ToolbarSelectionResult taskSelection(")).output(mark("box", "firstUpperCase")).output(literal("Box box, io.intino.alexandria.ui.model.Catalog catalog, String option, java.util.List<")).output(mark("itemClass")).output(literal("> selection, UISession session) {\n\treturn io.intino.alexandria.ui.model.toolbar.ToolbarSelectionResult.none();\n}")),
				rule().condition((allTypes("opencatalog", "operation"))).output(expression().output(mark("openCatalogOperationFilter"))),
				rule().condition((allTypes("operation", "opencatalogselection"))).output(expression().output(mark("openCatalogSelectionOperationFilter"))).output(literal("\n")).output(mark("openCatalogSelectionOperation")),
				rule().condition((trigger("opencatalogoperationfilter"))).output(literal("public static boolean openCatalogFilter(")).output(mark("box", "firstUpperCase")).output(literal("Box box, io.intino.alexandria.ui.model.")).output(mark("ownerClass")).output(literal(" ")).output(mark("ownerClass", "firstLowerCase")).output(literal(", Object object, UISession session) {\n\treturn true;\n}")),
				rule().condition((trigger("opencatalogselectionoperationfilter"))).output(literal("public static boolean openCatalogSelectionFilter(")).output(mark("box", "firstUpperCase")).output(literal("Box box, io.intino.alexandria.ui.model.")).output(mark("ownerClass")).output(literal(" ")).output(mark("ownerClass", "firstLowerCase")).output(literal(", java.util.List<")).output(mark("itemClass")).output(literal("> selection, Object object, UISession session) {\n\treturn true;\n}")),
				rule().condition((trigger("opencatalogselectionoperation"))).output(literal("public static io.intino.alexandria.ui.model.toolbar.ToolbarSelectionResult openCatalogSelection(")).output(mark("box", "firstUpperCase")).output(literal("Box box, io.intino.alexandria.ui.model.")).output(mark("ownerClass")).output(literal(" ")).output(mark("ownerClass", "firstLowerCase")).output(literal(", java.util.List<")).output(mark("itemClass")).output(literal("> selection, java.util.List<Object> openCatalogSelection, UISession session) {\n\treturn io.intino.alexandria.ui.model.toolbar.ToolbarSelectionResult.none();\n\n}"))
		);
	}
}